name: Node CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run ng -- build --configuration="production" 
      env:
        CI: true
    - name: AWS S3 Sync
      uses: opspresso/action-s3-sync@v0.2.1
      env:       
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        FROM_PATH: "./dist/"
        DEST_PATH: "s3://a-my-world/"
        OPTIONS: "--acl public-read"     
    - name: Invalidate Cloudfront Distribution
      uses: awact/cloudfront-action@master
      env:
        SOURCE_DIR: './public'
        AWS_REGION: 'eu-central-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
